mod cli;
mod framing;
mod metrics;
mod payload;
mod scenarios;

// Include prost-generated protobuf code.
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/pico.rs"));
}

use clap::Parser;
use cli::{Cli, Command, Role};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Redis(scenario) => match scenario.role {
            Role::Sender(args) => scenarios::redis::run_sender(args).await?,
            Role::Receiver(args) => {
                scenarios::redis::run_receiver(args).await?;
            }
        },
        Command::Quic(scenario) => match scenario.role {
            Role::Sender(args) => scenarios::quic::run_sender(args).await?,
            Role::Receiver(args) => {
                scenarios::quic::run_receiver(args).await?;
            }
        },
        Command::Tcp(scenario) => match scenario.role {
            Role::Sender(args) => scenarios::tcp::run_sender(args).await?,
            Role::Receiver(args) => {
                scenarios::tcp::run_receiver(args).await?;
            }
        },
        Command::Mqtt(scenario) => match scenario.role {
            Role::Sender(args) => scenarios::mqtt::run_sender(args).await?,
            Role::Receiver(args) => {
                scenarios::mqtt::run_receiver(args).await?;
            }
        },
        Command::Report(args) => {
            generate_report(args)?;
        }
    }

    Ok(())
}

fn generate_report(args: cli::ReportArgs) -> anyhow::Result<()> {
    println!("Generating HTML report from {} file(s)…", args.files.len());
    if args.files.is_empty() {
        anyhow::bail!("No input files provided. Usage: pico-launcher report results/*.json");
    }
    // The report is generated by report/generate.py; print a helpful message.
    println!(
        "Run:  python3 report/generate.py {} --output {}",
        args.files.join(" "),
        args.output,
    );
    println!("Or pass the files directly to the Python script for a full HTML dashboard.");
    Ok(())
}
